# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cache.proto for package 'cache'

require 'grpc'
require_relative 'cache_pb'

module Cache
  module CacheHub
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'cache.CacheHub'

      rpc :GetStatus, Cache::StatusRequest, Cache::StatusResponse
    end

    Stub = Service.rpc_stub_class
  end
end
