# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cache.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cache.proto", :syntax => :proto3) do
    add_message "cache.StatusRequest" do
      optional :name, :string, 1
    end
    add_message "cache.StatusResponse" do
      optional :message, :string, 1
    end
  end
end

module Cache
  StatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache.StatusRequest").msgclass
  StatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache.StatusResponse").msgclass
end
